### ISSUE TITLE
Volunteer form

### ISSUE THREAD

**Issue by elliottsj** [cssu/cssu.ca-old#13]
Create a Google Forms form for volunteer signup.

Path should be `/volunteer`

**Comment by arkon** [comment]
Fields:
- Name
- Email
- Year of study
- Major/minor/specialist
- Shirt size
- Time commitment
- Phone number

**Comment by jwebbed** [comment]
I'm assuming you got those from Zoe but a thought that passes my mind is we might want a copy of their schedule. We will also want their utorid.

**Comment by elliottsj** [comment]
Schedule isn't really feasible; neither Google Forms nor TypeForm let people enter/share their calendar. Might be something out there that works, but I haven't found anything.

Closed via #15
