### ISSUE TITLE
Add different types of events by host

### ISSUE THREAD

**Issue by jwebbed** [cssu/cssu.ca-old#16]
So we can post a ton of different events without spamming facebook. Preferably make this visibly different so we'll probably need to get @arkon involved on this. (Make CSSU events show more clearly)

**Comment by arkon** [comment]
What are some examples of different types?

**Comment by elliottsj** [comment]
Probably 'CSSU'/'DCS'/'PEY' or along those lines?

**Comment by jwebbed** [comment]
Yea, or just make it's CSSU or something else. Like give a special colour to CSSU and DCS (different colour but just a specific colour) then give a last colour to everything else where we can let it be a variable so we can just write it there.

**Comment by elliottsj** [comment]
WIP #18
