### ISSUE TITLE
Website is not currently auto-upating

### ISSUE THREAD

**Issue by jwebbed** [cssu/cssu.ca-old#40]
http://cssu.ca/events/2015/09/12/CS-Frosh_Day/ is still live despite the fact that it should have expired when rebuilt at midnight. Locally I can confirm that the post is not being rebuilt. It's probably worth considering some system for archiving old event posts that are potentially visible publicly for posterities sake. Worth consulting @elliottsj on this one.

**Comment by elliottsj** [comment]
There should be a cron job configured on the server which [redeploys every day at midnight](https://github.com/cssu/cdf-scripts/blob/master/config/schedule.rb#L7). IIRC, @xMrWhite reconfigured the crontab in April; the most recent scheduled backup completed back on April 8:

<img width="742" alt="screenshot 2015-09-13 16 01 31" src="https://cloud.githubusercontent.com/assets/2177366/9838654/d5009ff0-5a30-11e5-9863-6777cc92b014.png">

Just configure the crontab again using [cdf-scripts](https://github.com/cssu/cdf-scripts#enabling-automated-cron-tasks) and automated deploys should work again.

**Comment by jwebbed** [comment]
I should probably mention that since I just redeployed the site that link should be dead and the bug shouldn't be visible anymore

**Comment by g3wanghc** [comment]
This is no longer an issue. 

Nightly build for cssu/cssu.ca via nightli.es is also working.
