### ISSUE TITLE
Use SVGs for CSSU logo + UofT text

### ISSUE THREAD

**Issue by arkon** [cssu/cssu.ca-old#44]

**Comment by qasim** [comment]
but ie6 support

**Comment by arkon** [comment]
pls I only considered IE9

**Comment by jwebbed** [comment]
Just reviewing the analytics, of all the sessions only 1.29% of them were made from Internet Explorer. None of those sessions used an older version than 9. Literally 0%.

![ss 2015-10-01 at 12 01 37](https://cloud.githubusercontent.com/assets/5453617/10226241/5cb48b44-6834-11e5-976b-3283a45f976e.png)

**Comment by qasim** [comment]
We're working on a complete rebranding. Stay tuned for next semester

**Comment by arkon** [comment]
Mah website ;_;
