### ISSUE TITLE
Dead sponsors links

### ISSUE THREAD

**Issue by g3wanghc** [cssu/cssu.ca-old#45]
Source:
http://cssu.ca/sponsors/

There are dead/inactive links on the sponsors page:
e.g. http://www.smartweek2014.com/ and http://uoftdev.ca/

We need should repopulate/clean-up the page for 2016-2017.

**Comment by qasim** [comment]
Ought to standardize the sponsor/partner heights as well. They're all over the place. I'll take this

**Comment by arkon** [comment]
Removed completely in f0c98119353505fb43fa010f7e9ba811c2000ebf
