### ISSUE TITLE
Mobile site-nav menu not doing anything

### ISSUE THREAD

**Issue by g3wanghc** [cssu/cssu.ca-old#47]
When the class `showmenu` is added to the `body`, any `click` event on the `body` will trigger the function `closeMenu`. The function disables the default action on the DOM, making redirections impossible.

**Comment by g3wanghc** [comment]
As suggested by @arkon: "It might be better to just check if e.target was inside the .trigger element instead of adding the class."

**Comment by arkon** [comment]
Done in cbd93451d156540b6c9e3cb8bdeddbdbdefffdb4
