### ISSUE TITLE
Remove CS frosh applications/Add interview registration

### ISSUE THREAD

**Issue by g3wanghc** [cssu/cssu.ca-old#57]
Remove the volunteers application forms this weekend, and replace it with interview registrations.

**Comment by arkon** [comment]
Are you letting anyone sign up for interview registrations?

**Comment by g3wanghc** [comment]
Hum, good question. I'm still debating if we should give everyone an interview. We can also lock it with invitation codes.

**Comment by g3wanghc** [comment]
No longer holding interviews.
