### ISSUE TITLE
Update the cssu.ca wiki.

### ISSUE THREAD

**Issue by g3wanghc** [cssu/cssu.ca-old#63]
Update the wiki to reflect the new dev/deploy procedures.

**Comment by elliottsj** [comment]
Deploy document should be up-to-date, no? https://github.com/cssu/cssu.ca/wiki/Deploying-to-CDF

Does anything need to be changed on https://github.com/cssu/cssu.ca/wiki/Development?

**Comment by g3wanghc** [comment]
According to @jwebbed, the instructions on https://github.com/cssu/cssu.ca/wiki/Deploying-to-CDF replaces /w/.

**Comment by elliottsj** [comment]
Shoot I think you're right. I've updated the wiki now.

Is the CSSU wiki (the MedieWiki one) gone now? I think we have a backup somewhere on the server

**Comment by g3wanghc** [comment]
Yeah. Just replaced it with the backup. The current deploy script excludes `/w/` so I think we should be fine now.

**Comment by g3wanghc** [comment]
This issue is resolved.
