### ISSUE TITLE
What happened to the CSSU wiki?

### ISSUE THREAD

**Issue by freeatnet** [cssu/cssu.ca-old#65]
Steps to reproduce:
1. Go to https://cssu.ca/
2. Click "Wiki" in the menu

Expected: Wiki.
Observed: 404.

Do we still have it?

**Comment by g3wanghc** [comment]
The servers update on CDF broke a lot of our hosted services. We decided to migrate the hosting on github pages atm. Potential long term solutions are to use an external hosting service like heroku (draft deploys there atm), or Adam's private server.

**Comment by elliottsj** [comment]
To provide some more context, we no longer have SSH access to our old web host, dbsrv1.teach.cs.toronto.edu (i.e. publicly 128.100.31.220), so we cannot deploy new content to that server or maintain the wiki. Currently the wiki (http://128.100.31.220/w/) has a database error:

<img width="950" alt="screenshot 2016-09-18 11 46 05" src="https://cloud.githubusercontent.com/assets/2177366/18617049/82f4070e-7d95-11e6-9ffd-b3e581af21fa.png">

I'd like to set up a new host for the wiki (perhaps on AWS or DigitalOcean or something else), but unfortunately the latest wiki backup I have access to is from April 8, 2015, so the data would be rather old.

**Comment by freeatnet** [comment]
Well, that sucks. Thank you for your replies, @elliottsj @g3wanghc!

**Comment by arkon** [comment]
FYI, it's back: http://cssu.cdf.toronto.edu/w/index.php/Main_Page

**Comment by arkon** [comment]
It's ded again

**Comment by elliottsj** [comment]
fwiw, seems like the database is stopped again:
```
cssuwww@dbsrv1$ mysql --user=cssuwww --protocol=tcp cssu_wordpress                                                                                                                                       cssuwww@dbsrv1
ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost' (111)
```

We'll have to get the admins to bring it back up for us

**Comment by g3wanghc** [comment]
god damn it ...

**Comment by arkon** [comment]
It's back for some reason...
