### ISSUE TITLE
Status page

### ISSUE THREAD

**Issue by arkon** [cssu/cssu.ca-old#74]
There should really just be a status page that shows things like microwave, ice cream sandwich, pizza pop, Soylent, etc. availability instead of all these separate meme sites. Could easily be editable via a YAML file.

**Comment by g3wanghc** [comment]
This is a really good idea. I am legit losing track of how many memes sites we have at this point.

**Comment by GohNicho** [comment]
But then we lose the novelty of single-serve pages

**Comment by arkon** [comment]
The meme sites can redirect to the status page.

**Comment by g3wanghc** [comment]
We can use a status board like http://dashing.io/.
