### ISSUE TITLE
Add photo gallery

### ISSUE THREAD

**Issue by jwebbed** [cssu/cssu.ca-old#9]

**Comment by arkon** [comment]
For event photos and stuff?

**Comment by elliottsj** [comment]
http://cssu.ca/gallery/
:kappa:

**Comment by arkon** [comment]
You can close this then :kappa:

**Comment by elliottsj** [comment]
Not sure the current gallery app is ideal though; probably a better PHP app out there

**Comment by elliottsj** [comment]
@jwebbed Do you think it's worth continuing to use http://cssu.ca/gallery/, or can we just link to Facebook photo albums? (Or use something to embed Facebook albums, like [this](http://www.embedsocial.com/index.php))

**Comment by jwebbed** [comment]
This is probably still worth doing

**Comment by arkon** [comment]
Honestly could just link to the Facebook page...?
