### ISSUE TITLE
Replace Google Maps

### ISSUE THREAD

**Issue by arkon** [cssu/cssu.ca-old#98]
The map in the footer is broken after Google's new API limits.

Also see https://www.inderapotheke.de/blog/farewell-google-maps

**Comment by jwebbed** [comment]
this is dumb, switch to iPhone

**Comment by arkon** [comment]
Wat

**Comment by MichaelSheinman** [comment]
Better switch to Leaflet or other open source platform, Google maps is extremely expensive nowadays.

**Comment by qasim** [comment]
RIP
